### ISSUE TITLE
Can you share the baseline implementation, too?

### ISSUE THREAD

**Issue by wjun0830** [Gank0078/ACR#2]
Hello. Thanks for the great work.

Besides, I was wondering if you can share your baseline implementation e.g., fixmatch.

Thank you.

**Comment by Gank0078** [comment]
For LTSSL setting, the construction of dataset in cifar.py is modified to adapt our long-tailed setting and there are not many other changes for the baseline. For SSL setting, the code in kekmodel/FixMatch-pytorch can achieve strong performance. So in my opinion, it is unlikely that the baseline will perform so poorly and you'd better double check the code.
