### ISSUE TITLE
Why use interleave and de_interleave? Why not just torch.cat?

### ISSUE THREAD

**Issue by machengcheng2016** [Gank0078/ACR#7]
Greetings,
I've been studying this wonderful work recently. I wonder why you use `interleave` and `de_interleave` functions in `train.py`? Can `torch.cat` do the same thing?

**Comment by Gank0078** [comment]
Thank you for your interest in our work. Our code is based on FixMatch where both functions are implemented. You can refer https://github.com/kekmodel/FixMatch-pytorch/issues/36 and https://github.com/google-research/fixmatch/issues/20#issuecomment-613010277 for more details.

**Comment by machengcheng2016** [comment]
I see. In my experiments, `torch.cat` and `interleave/de_interleave` show very similar performances.
